import localFont from 'next/font/local';
import './globals.css';
import './about/page';
import { Noto_Sans_JP } from 'next/font/google';

const noto_sans = Noto_Sans_JP({
  style: 'normal',
  subsets: ['latin'],
  weight: '400',
  variable: ' --font-notosans',
});
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${noto_sans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
