import localFont from 'next/font/local';
import './globals.css';
import './about/page';
import { Lato } from 'next/font/google';

export const lato_init = Lato({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lato',
  weight: ['300', '400'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${lato_init.variable}`}>
        <main className='lato-light'>{children}</main>
      </body>
    </html>
  );
}
